name: dev

on: [pull_request]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.1
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm knip
      - run: pnpm -r exec tsc --noEmit
      - run: pnpm run prepare-release
      - run: pnpm --filter @rttui/test-lib-import exec playwright install --with-deps
      - run: pnpm --filter @rttui/test-lib-import exec vitest
      - run: pnpm exec changeset publish
