name: publish

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.1
      - run: pnpm --filter './packages/*' install
      - run: pnpm lint
      - run: pnpm knip
      - run: pnpm -r exec tsc --noEmit
      - run: bun run scripts/prepare_release.ts

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.1
      - run: pnpm --filter './packages/*' install
      - run: pnpm lint
      - run: pnpm knip
      - run: pnpm -r exec tsc --noEmit
      - run: bun run scripts/prepare_release.ts
      - run: |
          echo '@ricsam:registry=https://registry.npmjs.org' >> .npmrc
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          echo '//registry.npmjs.org/:always-auth=true' >> .npmrc
      - name: changeset publish
        run: pnpm exec changeset publish --access=public --registry=https://registry.npmjs.org/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
